

def method(name):  # Выбор сервиса API
    methods = {'futures': 'tinkoff.public.invest.api.contract.v1.InstrumentsService/Futures',
               'bonds': 'tinkoff.public.invest.api.contract.v1.InstrumentsService/Bonds',
               'etfs': 'tinkoff.public.invest.api.contract.v1.InstrumentsService/Etfs',
               'currencies': 'tinkoff.public.invest.api.contract.v1.InstrumentsService/Currencies',
               'shares': 'tinkoff.public.invest.api.contract.v1.InstrumentsService/Shares',
               'getdividends': 'tinkoff.public.invest.api.contract.v1.InstrumentsService/GetDividends',
               'shareBy': 'tinkoff.public.invest.api.contract.v1.InstrumentsService/ShareBy',
               'futureBy': 'tinkoff.public.invest.api.contract.v1.InstrumentsService/FutureBy',
               'bondBy': 'tinkoff.public.invest.api.contract.v1.InstrumentsService/BondBy',
               'etfBy': 'tinkoff.public.invest.api.contract.v1.InstrumentsService/EtfBy',
               'CurrencyBy': 'tinkoff.public.invest.api.contract.v1.InstrumentsService/CurrencyBy',
               'GetAccuruedInterests': 'tinkoff.public.invest.api.contract.v1.InstrumentsService/GetAccruedInterests',
               'GetFuturesMargin': 'tinkoff.public.invest.api.contract.v1.InstrumentsService/GetFuturesMargin',
               'GetInstrumentBy': 'tinkoff.public.invest.api.contract.v1.InstrumentsService/GetInstrumentBy',
               'GetAccounts':'tinkoff.public.invest.api.contract.v1.UsersService/GetAccounts',
               'GetInfo':'tinkoff.public.invest.api.contract.v1.UsersService/GetInfo',
               'GetUserTariff':'tinkoff.public.invest.api.contract.v1.UsersService/GetUserTariff',
               'GetCandles':'tinkoff.public.invest.api.contract.v1.MarketDataService/GetCandles',
               'GetLastPrice':'tinkoff.public.invest.api.contract.v1.MarketDataService/GetLastPrices',
               'GetOrderBook':'tinkoff.public.invest.api.contract.v1.MarketDataService/GetOrderBook',
               'GetTradingStatus':'tinkoff.public.invest.api.contract.v1.MarketDataService/GetTradingStatus',
               'GetPortfolio':'tinkoff.public.invest.api.contract.v1.OperationsService/GetPortfolio',
               'GetOperations':'tinkoff.public.invest.api.contract.v1.OperationsService/GetOperations',
               'GetPositions':'tinkoff.public.invest.api.contract.v1.OperationsService/GetPositions',
               'GetWithdrawLimits': 'tinkoff.public.invest.api.contract.v1.OperationsService/GetWithdrawLimits',
               'GetOrders':'tinkoff.public.invest.api.contract.v1.OrdersService/GetOrders',
               'CancelOrder':'tinkoff.public.invest.api.contract.v1.OrdersService/CancelOrder',
               'GetOrderState':'tinkoff.public.invest.api.contract.v1.OrdersService/GetOrderState',
               'PostOrder':'tinkoff.public.invest.api.contract.v1.OrdersService/PostOrder',
               'CancelStopOrder':'tinkoff.public.invest.api.contract.v1.StopOrdersService/CancelStopOrder',
               'GetStopOrders':'tinkoff.public.invest.api.contract.v1.StopOrdersService/GetStopOrders',
               'PostStopOrder':'tinkoff.public.invest.api.contract.v1.StopOrdersService/PostStopOrder',
               'CancelSandboxOrder':'tinkoff.public.invest.api.contract.v1.SandboxService/CancelSandboxOrder',
               'GetSandboxAccounts':'tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxAccounts',
               'GetSandboxOperations':'tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxOperations',
               'GetSandboxOrderState':'tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxOrderState',
               'GetSandboxOrders':'tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxOrders',
               'GetSandboxPortfolio':'tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxPortfolio',
               'GetSandboxPositions':'tinkoff.public.invest.api.contract.v1.SandboxService/GetSandboxPositions',
               'PostSandboxOrder':'tinkoff.public.invest.api.contract.v1.SandboxService/PostSandboxOrder',
               'SandboxPayIn':'tinkoff.public.invest.api.contract.v1.SandboxService/SandboxPayIn',
               'OpenSandboxAccount':'tinkoff.public.invest.api.contract.v1.SandboxService/OpenSandboxAccount',
               'CloseSandboxAccount':'tinkoff.public.invest.api.contract.v1.SandboxService/CloseSandboxAccount'
               }
    
    return methods[name]